### PR TITLE
Feature/add match type

### PR DESCRIPTION
**Pull request by florobarotjr**
Opening for early feedback but don't merge yet.

See #141

### CODE REVIEW

**Comment by marksteve** [comment]
@florobarotjr screen shot 2018-08-28 at 1 06 17 pm

**Comment by florobarotjr** [comment]
Odd, I'm getting exact matches on my local copy of the branch :| @marksteve

**Comment by marksteve** [comment]
I just tried again both in this branch and master. Master gets only 4 partial matches. This branch gets 12. 

[FamilyDOC Branches - Sheet1.csv.zip](https://github.com/thinkingmachines/linksight/files/2328481/FamilyDOC.Branches.-.Sheet1.csv.zip)

**Comment by florobarotjr** [comment]
@marksteve  ah, thanks for providing the CSV. I was using a more cleaned up version of that dataset.

Seems like the change is working as intended in that if we can't find a lower interlevel match, we'll provide whatever higher interlevel match we find and 'No match' as an option. Before, those are marked as exact matches even if we weren't able to find the barangay data.

Having said that, the reason why `Sabang` is not being matched in the example is because of the substring matching :(. The City field is `Dasmarinas. Cavite`. It found `Cavite` first in the reference file so it didn't match to `Dasmarinas` at all.

**Comment by marksteve** [comment]
Discussed with @florobarotjr that this is an edge case that we shouldn't be handling for now.

**Pull request merged**
